server:
  port: 9999

spring:
  application:
    name: term2-spring-inside
  profiles:
    active: dev
  datasource:
    postgres:
      url: jdbc:postgresql://localhost:5432/edu-postgres
      username: password
      password: password
      driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    path: /swagger-ui
  swagger-ui:
    url: /swagger.yml
    path: /swagger-ui

